# Generated by Django 4.2.2 on 2023-06-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('F', 'M'), ('M', 'F')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('escola_de_origem', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=3, null=True)),
                ('turma', models.CharField(max_length=1, null=True)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('telefone_responsavel', models.CharField(max_length=13)),
                ('parentesco', models.CharField(max_length=255)),
            ],
        ),
    ]
